In [1]:
# 載入 NumPy 套件
import numpy as np

# 檢查正確載入與版本
print(np)
print(np.__version__)

<module 'numpy' from 'C:\\Users\\user\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>
1.20.2


In [2]:
a = np.arange(15).reshape(3, 5)
print(a) # 利用 print(...) 印出陣列
a # 利用 Jupyter 印出陣列

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
# 陣列的常用屬性

print(a.dtype) # int32
print(a.itemsize) # 8

int32
4


In [4]:
# numpy 中的型態判斷

print(a.dtype == 'int32') 
print(a.dtype is 'int32') 
print(a.dtype is np.int32) 

True
False
False


In [5]:
# 資料型態的正確用法

print(a.dtype == 'int32') # True
print(a.dtype == np.int32) # True
print(a.dtype is np.dtype('int32')) # True

True
True
True


# 作業目標
熟悉陣列維度轉換，並且會擷取需要資料
作業重點
使用reshap須注意order用法
where可以運用邏輯條件擷取資料

題目:
1.將下列陣列(array1)，轉成維度為(5X6)的array，順序按列填充。(hint:order="F")
2.呈上題的array，找出被6除餘1的數的索引

In [6]:
import numpy as np

In [7]:
#1.將下列清單(list1)，轉成維度為(5X6)的array，順序按列填充。(hint:order="F")
array1 = np.array(range(30))
ans1=array1.reshape(5,6,order='F')
print(ans1)

[[ 0  5 10 15 20 25]
 [ 1  6 11 16 21 26]
 [ 2  7 12 17 22 27]
 [ 3  8 13 18 23 28]
 [ 4  9 14 19 24 29]]


In [8]:
#2.呈上題的array，找出被6除餘1的數的索引
ans2=np.where(ans1%6==1)
print(ans2)

(array([0, 1, 2, 3, 4], dtype=int64), array([5, 0, 1, 2, 3], dtype=int64))


In [9]:
ans1[ans2] #check the answer

array([25,  1,  7, 13, 19])