作業
1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

In [1]:
import numpy as np
print(np.zeros((2, 3)))
print(np.empty((2, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [2]:
%timeit np.zeros(10000)
%timeit np.empty(10000)

3.71 µs ± 189 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
901 ns ± 35.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [3]:
#np.zero():always 0. ###slower###
#np.empty():Random number closted to 0, depending on memory condition. ###faster###


2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數

In [4]:
# 參考解答
a = np.random.rand(2, 3)
print(a)
print(a // 1)
print(np.floor(a))
print(np.array(a, dtype = 'int32'))

[[0.25786684 0.8491352  0.09351138]
 [0.64495567 0.90985073 0.53148766]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0]
 [0 0 0]]


3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

In [5]:
m = 20
n = 40
c = np.random.randint(m,n,(2,3))
print(c)

[[29 24 26]
 [24 37 31]]


作業目標

在一個陣列中放入多屬性陣列，進一步對陣列做運算

作業重點

在建立結構化陣列前需要先設定屬性，在做運算時須注意資料屬性

題目:

name_list = ['小明','小華','小菁','小美','小張','John','Mark','Tom']

sex_list = ['boy','boy','girl','girl','boy','boy','boy','boy']

weight_list = [67.5,75.3,50.1,45.5,80.8,90.4,78.4,70.7]

rank_list = [8,1,5,4,7,6,2,3]

myopia_list = [True,True,False,False,True,True,False,False]

1. 將上列list依照['name', 'sex', 'weight', 'rank', 'myopia']順序擺入array，並且資料型態順序擺入[Unicode,Unicode,float,int,boolean]
2. 呈上題，將array中體重(weight)數據集取出算出全部平均體重
3. 呈上題，進一步算出男生(sex欄位是boy)平均體重、女生(sex欄位是girl)平均體重

In [6]:
name_list = ['小明','小華','小菁','小美','小張','John','Mark','Tom']
sex_list = ['boy','boy','girl','girl','boy','boy','boy','boy']
weight_list = [67.5,75.3,50.1,45.5,80.8,90.4,78.4,70.7]
rank_list = [8,1,5,4,7,6,2,3]
myopia_list = [True,True,False,False,True,True,False,False]

In [7]:
#1. 將上列list依照['name', 'sex', 'weight', 'rank', 'myopia']順序擺入array，並且資料型態順序擺入[Unicode,Unicode,float,int,boolean]
dt = np.dtype({'names':('name', 'sex', 'weight', 'rank', 'myopia'), 
               'formats':('U10', 'U6', float, int, bool)})
table = np.zeros(8, dtype=dt)
table['name'] = name_list
table['sex'] = sex_list
table['weight'] = weight_list
table['rank'] = rank_list
table['myopia'] = myopia_list


In [8]:
#2. 呈上題，將array中體重(weight)數據集取出算出全部平均體重
np.mean(table['weight'])

69.8375

In [9]:
#3. 呈上題，進一步算出男生(sex欄位是boy)平均體重
np.mean(table['weight'][table['sex'] == 'boy'])

77.18333333333332

In [10]:
#3. 呈上題，進一步算出女生(sex欄位是girl)平均體重
np.mean(table['weight'][table['sex'] == 'girl'])

47.8