1. [簡答題] 請問下列程式碼，運算結果分別為何？



a = np.array( [20,30,40,50] )

b = np.array( [1,2,3,4] ) 

c = 1

d = np.array( [1] )

e = np.array( [1,2] ) 



2. 如何在不用迴圈的情況下計算 (A+B)*(-A/2) ？那用迴圈怎麼做？

3. 請問如何計算「1x6 的單位矩陣」和「6x1 的單位矩陣」的內積和外積？

In [1]:
#1
import numpy as np
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] )
c = 1
d = np.array( [1] )
e = np.array( [1,2] )


print(a + a)
print(a + b)
print(a + c)
print(a + d)
print(a.reshape(-1,1) + e)
print(a + e) #error

[ 40  60  80 100]
[21 32 43 54]
[21 31 41 51]
[21 31 41 51]
[[21 22]
 [31 32]
 [41 42]
 [51 52]]


ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [2]:
#2
A = np.ones(3)*1
B = np.ones(3)*2

print((A+B)*(-A/2))


[-1.5 -1.5 -1.5]


In [3]:
#3
A = np.ones((1,6))
B = np.ones((6,1))
print(A*B)
print(A@B)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[6.]]


作業目標:
嘗試練習log的函式並應用
作業重點:
學員需要複習log的轉換方式
熟悉運用指數函數以及對數函數

題目:
運用投影片中的分貝公式回答下列問題。
1.正常的談話的聲壓為20000微巴斯卡，請問多少分貝?
2.30分貝的聲壓會是50分貝的幾倍?

GdB=20*np.log10(V1/V0)

In [4]:
import numpy as np 

In [5]:
#1.正常的談話的聲壓為20000微巴斯卡，請問多少分貝?
#請寫下程式
V1 = 20000
V0 = 20
ans1=20*np.log10(V1/V0)
print(ans1)

60.0


In [6]:
#2.30分貝的聲壓會是50分貝的幾倍?
#公式移項過後可以得到 V1 = ?
#請寫下程式
def V1(GDB):
  return 20*np.power(10,GDB/20)  
V1_GDB30=V1(30)
V1_GDB50=V1(50)
ans2=V1_GDB30/V1_GDB50
print(ans2)

0.09999999999999999


In [7]:
#若直接做相除
ans2_2 = 10**(30/20-50/20)
print(ans2_2)

0.1
