[作業目標]

產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。

試著從一個隨機陣列中，找出比 0.5 大的數有幾個？


In [1]:
#1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。

import numpy as np
oneD = np.arange(1,12)
oneD[np.in1d(oneD,np.arange(4,7))] *=-1
print(oneD)

oneD = np.arange(1,12)
oneD[(oneD <= 6) & (oneD >= 3)] *= -1
print(oneD)

[ 1  2  3 -4 -5 -6  7  8  9 10 11]
[ 1  2 -3 -4 -5 -6  7  8  9 10 11]


In [2]:
#2.試著從一個隨機陣列中，找出比 0.5 大的數有幾個？
A = np.random.rand(3, 6)
print(A)
print(A[A > 0.5].size)
print(len(A[A > 0.5]))
print(np.sum(A > 0.5))

[[0.40876232 0.45687098 0.97277306 0.98465035 0.09318944 0.43563024]
 [0.94557519 0.29041941 0.20791837 0.48388401 0.51126277 0.24312722]
 [0.98474742 0.99129134 0.64801587 0.66773705 0.37258409 0.60943493]]
9
9
9


作業目標

計算有缺失值的資料，統計量實作

作業重點

當遇到缺失值有函式可以處理，不須額外寫程式刪除

計算統計量時不能出現缺失值

題目:

english_score = np.array([55,89,76,65,48,70])

math_score = np.array([60,85,60,68,np.nan,60])

chinese_score = np.array([65,90,82,72,66,77])

上3列共六位同學的英文、數學、國文成績，第一個元素代表第一位同學，舉例第一位同學英文55分、數學60分、國文65分，今天第五位同學因某原因沒來考試，導致數學成績缺值，運用上列數據回答下列問題。

請計算各科成績平均、最大值、最小值、標準差，其中數學缺一筆資料可忽略?

第五位同學補考數學後成績為55，請計算補考後數學成績平均、最大值、最小值、標準差?

用補考後資料找出與國文成績相關係數最高的學科?

In [3]:
import numpy as np

In [4]:
english_score = np.array([55,89,76,65,48,70])
math_score = np.array([60,85,60,68,np.nan,60])
chinese_score = np.array([65,90,82,72,66,77])

In [5]:
#1. 請計算各科成績平均、最大值、最小值、標準差，其中數學缺一筆資料可忽略?
score_all= np.vstack((english_score,math_score,chinese_score))
ans1_1=np.nanmean(score_all,axis=1)
ans1_2=np.nanmax(score_all,axis=1)
ans1_3=np.nanmin(score_all,axis=1)
ans1_4=np.nanstd(score_all,axis=1)
ans1=np.vstack((ans1_1,ans1_2,ans1_3,ans1_4)).T
print(ans1)

[[67.16666667 89.         48.         13.43399502]
 [66.6        85.         60.          9.70772888]
 [75.33333333 90.         65.          8.8254682 ]]


In [6]:
#2. 第五位同學補考數學後成績為55，請計算補考後數學成績平均、最大值、最小值、標準差?
math_score[4]=55

score_all_new= np.vstack((english_score,math_score,chinese_score))
ans1_1=np.nanmean(score_all_new,axis=1)
ans1_2=np.nanmax(score_all_new,axis=1)
ans1_3=np.nanmin(score_all_new,axis=1)
ans1_4=np.nanstd(score_all_new,axis=1)
ans2=np.vstack((ans1_1,ans1_2,ans1_3,ans1_4)).T
print(ans2)

[[67.16666667 89.         48.         13.43399502]
 [64.66666667 85.         55.          9.86013297]
 [75.33333333 90.         65.          8.8254682 ]]


In [7]:
#3. 用補考後資料找出與國文成績相關係數最高的學科?

In [8]:
np.corrcoef(score_all_new)
#the highest corrcoef is Engilsh

array([[1.        , 0.7855563 , 0.97792828],
       [0.7855563 , 1.        , 0.74056803],
       [0.97792828, 0.74056803, 1.        ]])