
1.   [簡答題] 請問下列這三種方法有什麼不同？

print(a.sum()) 

print(np.sum(a))

print(sum(a)) 

2.   請對一個 5x5 的隨機矩陣作正規化的操作。

3.   請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。

In [1]:
import numpy as np

a =np.arange(10000)

print(a.sum())
print(np.sum(a))
print(sum(a))

%timeit a.sum()
%timeit np.sum(a)
%timeit sum(a)

49995000
49995000
49995000
7.29 µs ± 394 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
9.04 µs ± 338 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
868 µs ± 98.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [2]:
# a.sum(),np.sum(a)和sum(a)可得相同結果
#但速度上來說 a.sum>np.sum(a)>sum(a)

In [3]:
#2. 請對一個 5x5 的隨機矩陣作正規化的操作。

A = np.random.random((5, 5))*100
norA = (A-A.min())/(A.max()-A.min())
print(A,norA,sep='\n')

[[44.47517334 20.60693329 24.08078829 26.27331629 49.64281349]
 [16.50994897 84.73375375 36.44604415  4.59926391 47.66159137]
 [82.37028815 62.88055479 10.24634728 44.01544047 97.80861772]
 [61.49762605 72.41378384 20.38554067 44.98961555 85.1637139 ]
 [62.37454607 23.01497228 89.91166159 71.96732223 23.51123953]]
[[0.42781017 0.17173887 0.20900825 0.23253087 0.48325139]
 [0.12778423 0.85972584 0.34166936 0.         0.46199577]
 [0.83436931 0.62527298 0.06058494 0.42287791 1.        ]
 [0.61043618 0.72755059 0.16936365 0.43332938 0.86433868]
 [0.61984425 0.19757361 0.91527721 0.72276071 0.20289783]]


In [4]:
# 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。
A = np.random.randint(1,100,10)
print(A)
A[A==np.max(A)]=-1
print(A)

[79 65 82 85 32 91 91 50  1 90]
[79 65 82 85 32 -1 -1 50  1 90]



1.將下列陣列(array1)，轉成維度為(5X6)的 array，順序按列填充。(hint:order="F")

2.呈上題的 array，找出被 6 除餘 1 的數的索引

In [5]:
#1.將下列陣列(array1)，轉成維度為(5X6)的 array，順序按列填充。(hint:order="F")

array1 = np.array(range(30))
print('按行填充:',array1.reshape(5,6),sep='\n')
print('按行填充:',array1.reshape(5,6,order='C'),sep='\n')
print('按列填充:',array1.reshape(5,6,order='F'),sep='\n')
array2=array1.reshape(5,6,order='F')

按行填充:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
按行填充:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
按列填充:
[[ 0  5 10 15 20 25]
 [ 1  6 11 16 21 26]
 [ 2  7 12 17 22 27]
 [ 3  8 13 18 23 28]
 [ 4  9 14 19 24 29]]


In [6]:
#2.呈上題的 array，找出被 6 除餘 1 的數的索引
np.where(array2%6==1)

(array([0, 1, 2, 3, 4], dtype=int64), array([5, 0, 1, 2, 3], dtype=int64))