請比較對一個 100 x 100 * 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。

如何從一個陣列中，找出出現頻率最高的數值與位置？

如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。

In [1]:
import numpy as np
import timeit

In [2]:
#1. 請比較對一個 1000 x 100 x 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。
Z = np.random.randint(0, 10, 1000000).reshape(100, 100, 100)

In [3]:
#No modify
%timeit -n 10 a = 2
Z += 1

24.3 ns ± 10.5 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [4]:
#falt
%timeit -n 10 a = 2

Z_method2 = []

for i in Z.flat:
    Z_method2.append(i+1)
Z_method2=np.array(Z_method2).reshape(100,100,100)

38.6 ns ± 13.6 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [5]:
#falt
%timeit -n 10 a = 2

Z_method3 = []

for i in np.nditer(Z, order = 'C'):
    Z_method3.append(i+1)

Z_method3_array = np.array(Z_method3, dtype = int).reshape(100,100,100)


34.3 ns ± 7.28 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [6]:
#2.如何從一個陣列中，找出出現頻率最高的數值與位置？
Z = np.random.randint(0,10,50)
print(Z)

uni,con=np.unique(Z,return_counts=True)
print('頻率最高的數值:',np.max(uni))
print('頻率最高的數值的次數:',con[np.argmax(uni)])
print('頻率最高的數值的位置:',np.where(Z==np.max(uni))[0])
#np.where()[0] 表示行索引，np.where()[1]表示列索引

[9 0 8 8 9 4 8 3 5 3 3 7 9 6 1 8 0 9 3 6 3 4 0 3 4 1 9 7 0 8 9 6 4 7 5 1 8
 2 4 4 3 9 0 4 6 8 3 6 7 9]
頻率最高的數值: 9
頻率最高的數值的次數: 8
頻率最高的數值的位置: [ 0  4 12 17 26 30 41 49]


In [7]:
#3.如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。
a = np.random.randint(10, size=6) 
print(a.tolist())
print(list(a))


b = np.random.randint(10, size=(3,4)) 
print(b.tolist())
print(list(b))


c = np.random.randint(10, size=(2,3,2)) 
print(c.tolist())
print(list(c))

[2, 9, 6, 0, 5, 9]
[2, 9, 6, 0, 5, 9]
[[4, 8, 6, 1], [1, 4, 8, 3], [3, 4, 1, 1]]
[array([4, 8, 6, 1]), array([1, 4, 8, 3]), array([3, 4, 1, 1])]
[[[0, 0], [0, 0], [0, 5]], [[1, 1], [3, 0], [6, 5]]]
[array([[0, 0],
       [0, 0],
       [0, 5]]), array([[1, 1],
       [3, 0],
       [6, 5]])]


In [8]:
tolist_ = lambda arr: list(map(tolist_, arr)) if isinstance(arr, np.ndarray) else arr #isinstance is faster than type()
tolist_(c)

[[[0, 0], [0, 0], [0, 5]], [[1, 1], [3, 0], [6, 5]]]

In [9]:
def tolist_2(arr):
    if (isinstance(arr, np.ndarray)):
        return(list(map(tolist_2, arr)))        
    else:
        return(arr)

tolist_2(c)

[[[0, 0], [0, 0], [0, 5]], [[1, 1], [3, 0], [6, 5]]]

array1 = np.array([[10, 8], [3, 5]])



運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?

運用上列array計算特徵值、特徵向量?

運用上列array計算SVD?

In [10]:
array1 = np.array([[10, 8], [3, 5]])

In [11]:
#1.運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
array2 = np.linalg.inv(array1 )
print( '反矩陣 = \n', array2 )

print('反矩陣乘上原矩陣為單位矩陣:\n',array1.dot(array2))

反矩陣 = 
 [[ 0.19230769 -0.30769231]
 [-0.11538462  0.38461538]]
反矩陣乘上原矩陣為單位矩陣:
 [[1. 0.]
 [0. 1.]]


In [12]:
#2.運用上列array計算特徵值、特徵向量?
print('eigenvalues:',np.linalg.eig(array1)[0],sep='\n')
print('eigenvectors:',np.linalg.eig(array1)[1],sep='\n')


eigenvalues:
[13.  2.]
eigenvectors:
[[ 0.93632918 -0.70710678]
 [ 0.35112344  0.70710678]]


In [13]:
#3.運用上列array計算SVD?
u, s, vh = np.linalg.svd(array1)
print(u)
print(s)
print(vh)

[[-0.91663818 -0.39971796]
 [-0.39971796  0.91663818]]
[13.94721714  1.86417116]
[[-0.74319741 -0.6690722 ]
 [-0.6690722   0.74319741]]
